export enum KeyManager {
	Message = 'key_message',
	EmailInvalid = 'emailErrorMessage',
	PasswordInvalid = 'passwordErrorMessage',
	FirstNameInValid = 'firstNameErrorMessage',
	LastNameInValid = 'lastNameErrorMessage',
	EmailDoesNotMatch = 'conFirmEmailErrorMessage',
	PasswordDoesNotMatch = 'conFirmPasswordErrorMessage',
	CompanyNameInvalid = 'companyNameInvalid',
	RegistrationNoInvalid = 'registrationNoInvalid',
	AddressNoInvalid = 'addressNoInvalid',
	VillageInvalid = 'villageInvalid',
	RoadInvalid = 'roadInvalid',
	ProvinceInvalid = 'provinceInvalid',
	DistrictInvalid = 'districtInvalid',
	SubDistrictInvalid = 'subDistrictInvalid',
	ZipCodeInvalid = 'zipCodeInvalid',
	AuditorLicenseInvalid = 'auditorLicenseInvalid',
	AuditorNameInvalid = 'auditorNameInvalid'
}