export const routeToMemberPage = '/companyInformation'
export const routeToSignin = '/signin'
export const routeToPageNonDisclosure = '/nonDisclosure'
export const routeToPageMyNonDisclosureAgreement = '/myNonDisclosureAgreement'
export const routerToPageTableEditNonDisclosure = '/tableEditNonDisclosure'
